version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=yourmongodburl
      - DASHSCOPE_API_KEY=yourapikey
      - NODE_ENV=production
      - NEXTAUTH_SECRET=your-nextauth-secret-key
      - NEXTAUTH_URL=http://localhost:4000
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "41434:41434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_HOST=0.0.0.0:41434
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '1.8'
        reservations:
          memory: 4G
          cpus: '1'

volumes:
  ollama_data:

