version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://wubowen97:970412qw@health.dpql5.mongodb.net/?retryWrites=true&w=majority&appName=health
      - OLLAMA_HOST=http://ollama:11434
      - NODE_ENV=production
      - NEXTAUTH_SECRET=your-nextauth-secret-key
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G

volumes:
  ollama_data:

